insert into public.loai_thiet_bi (ma_loai, ten_loai, ghi_chu)
values
  ('SIM_PKI', 'Sim PKI', 'Thiet bi chung thu so'),
  ('TOKEN', 'Token', 'Thiet bi chung thu so'),
  ('TOKEN_MAT', 'Token mật', 'Thiet bi chung thu so')
on conflict (ma_loai) do update
set
  ten_loai = excluded.ten_loai,
  ghi_chu = excluded.ghi_chu;

create table if not exists public.thiet_bi_chung_thu_so (
  id integer generated by default as identity primary key,
  thiet_bi_id integer not null references public.thiet_bi(id) on delete restrict,
  nguoi_su_dung_id integer not null references public.nguoi_dung(id) on delete restrict,
  so_hieu_chung_thu_so character varying not null,
  ngay_hieu_luc date not null,
  ngay_het_hieu_luc date not null,
  thoi_diem_gia_han_gan_nhat timestamp with time zone,
  thoi_diem_thay_doi_thong_tin_gan_nhat timestamp with time zone,
  thoi_diem_thu_hoi timestamp with time zone,
  ghi_chu character varying,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint thiet_bi_chung_thu_so_thiet_bi_id_key unique (thiet_bi_id),
  constraint thiet_bi_chung_thu_so_so_hieu_key unique (so_hieu_chung_thu_so),
  constraint thiet_bi_chung_thu_so_ngay_check check (ngay_het_hieu_luc >= ngay_hieu_luc)
);

create table if not exists public.lich_su_chung_thu_so (
  id integer generated by default as identity primary key,
  thiet_bi_id integer not null references public.thiet_bi(id) on delete restrict,
  loai_su_kien character varying not null,
  thoi_diem_su_kien timestamp with time zone not null default now(),
  nguoi_su_dung_id_truoc integer references public.nguoi_dung(id) on delete set null,
  nguoi_su_dung_id_sau integer references public.nguoi_dung(id) on delete set null,
  so_hieu_chung_thu_so_truoc character varying,
  so_hieu_chung_thu_so_sau character varying,
  ngay_hieu_luc_truoc date,
  ngay_hieu_luc_sau date,
  ngay_het_hieu_luc_truoc date,
  ngay_het_hieu_luc_sau date,
  ghi_chu character varying,
  created_at timestamp with time zone not null default now(),
  constraint lich_su_chung_thu_so_loai_su_kien_check check (loai_su_kien in ('cap_moi', 'gia_han', 'thay_doi_thong_tin', 'thu_hoi')),
  constraint lich_su_chung_thu_so_ngay_truoc_check check (ngay_het_hieu_luc_truoc is null or ngay_hieu_luc_truoc is null or ngay_het_hieu_luc_truoc >= ngay_hieu_luc_truoc),
  constraint lich_su_chung_thu_so_ngay_sau_check check (ngay_het_hieu_luc_sau is null or ngay_hieu_luc_sau is null or ngay_het_hieu_luc_sau >= ngay_hieu_luc_sau)
);

create index if not exists idx_thiet_bi_chung_thu_so_ngay_het_hieu_luc
  on public.thiet_bi_chung_thu_so (ngay_het_hieu_luc);

create index if not exists idx_thiet_bi_chung_thu_so_nguoi_su_dung_id
  on public.thiet_bi_chung_thu_so (nguoi_su_dung_id);

create index if not exists idx_thiet_bi_chung_thu_so_thoi_diem_thu_hoi
  on public.thiet_bi_chung_thu_so (thoi_diem_thu_hoi);

create index if not exists idx_thiet_bi_chung_thu_so_bao_cao_hieu_luc
  on public.thiet_bi_chung_thu_so (ngay_het_hieu_luc, thoi_diem_thu_hoi);

create index if not exists idx_lich_su_chung_thu_so_thiet_bi_id
  on public.lich_su_chung_thu_so (thiet_bi_id);

create index if not exists idx_lich_su_chung_thu_so_loai_su_kien
  on public.lich_su_chung_thu_so (loai_su_kien);

create index if not exists idx_lich_su_chung_thu_so_thoi_diem_su_kien
  on public.lich_su_chung_thu_so (thoi_diem_su_kien);

create or replace view public.v_bao_cao_chung_thu_so
with (security_invoker = true)
as
select
  cts.id as thiet_bi_chung_thu_so_id,
  tb.id as thiet_bi_id,
  tb.ma_thiet_bi as so_hieu_thiet_bi,
  tb.ten_thiet_bi,
  lt.id as loai_thiet_bi_id,
  lt.ten_loai as loai_thiet_bi,
  nd.id as nguoi_su_dung_id,
  nd.ho_ten as nguoi_su_dung,
  coalesce(nd.phong_ban_id, tb.phong_ban_id) as phong_ban_id,
  pb.ten_phong_ban,
  cts.so_hieu_chung_thu_so,
  cts.ngay_hieu_luc,
  cts.ngay_het_hieu_luc,
  cts.thoi_diem_gia_han_gan_nhat,
  cts.thoi_diem_thay_doi_thong_tin_gan_nhat,
  cts.thoi_diem_thu_hoi,
  cts.ngay_het_hieu_luc + 30 as ngay_can_thu_hoi,
  cts.ngay_het_hieu_luc - current_date as so_ngay_con_lai,
  case
    when cts.thoi_diem_thu_hoi is not null then 'da_thu_hoi'
    when current_date > cts.ngay_het_hieu_luc + 30 then 'can_thu_hoi'
    when current_date > cts.ngay_het_hieu_luc then 'het_han_cho_gia_han'
    when cts.ngay_het_hieu_luc <= current_date + 30 then 'sap_het_han'
    else 'dang_hieu_luc'
  end as trang_thai,
  cts.ghi_chu,
  cts.created_at,
  cts.updated_at
from public.thiet_bi_chung_thu_so cts
join public.thiet_bi tb on tb.id = cts.thiet_bi_id
left join public.loai_thiet_bi lt on lt.id = tb.loai_thiet_bi_id
left join public.nguoi_dung nd on nd.id = cts.nguoi_su_dung_id
left join public.phong_ban pb on pb.id = coalesce(nd.phong_ban_id, tb.phong_ban_id);

alter table public.thiet_bi_chung_thu_so enable row level security;
alter table public.lich_su_chung_thu_so enable row level security;

comment on table public.thiet_bi_chung_thu_so is 'Thong tin hien hanh cua thiet bi chung thu so; moi thiet bi vat ly co mot ban ghi hien hanh.';
comment on table public.lich_su_chung_thu_so is 'Lich su su kien cap moi, gia han, thay doi thong tin, thu hoi cua thiet bi chung thu so.';
comment on view public.v_bao_cao_chung_thu_so is 'View bao cao chung thu so voi trang thai hieu luc tinh theo ngay hien tai va quy tac thu hoi sau 30 ngay qua han.';
