alter table public.thiet_bi_chung_thu_so
  drop constraint if exists thiet_bi_chung_thu_so_thiet_bi_id_key;

alter table public.thiet_bi_chung_thu_so
  add column if not exists email character varying,
  add column if not exists ten_chung_thu_so character varying,
  add column if not exists loai_chung_thu_so character varying,
  add column if not exists to_chuc character varying,
  add column if not exists thong_tin_chung text,
  add column if not exists id_chung_thu_so_nguon character varying,
  add column if not exists da_gia_han boolean not null default false,
  add column if not exists la_hien_hanh boolean not null default true,
  add column if not exists chung_thu_goc_id integer references public.thiet_bi_chung_thu_so(id) on delete set null,
  add column if not exists chung_thu_thay_the_id integer references public.thiet_bi_chung_thu_so(id) on delete set null,
  add column if not exists ly_do_thu_hoi text;

update public.thiet_bi_chung_thu_so cts
set
  email = coalesce(
    cts.email,
    (
      select nd.email
      from public.nguoi_dung nd
      where nd.id = cts.nguoi_su_dung_id
    )
  ),
  ten_chung_thu_so = coalesce(
    cts.ten_chung_thu_so,
    (
      select nd.ho_ten
      from public.nguoi_dung nd
      where nd.id = cts.nguoi_su_dung_id
    )
  ),
  loai_chung_thu_so = coalesce(
    cts.loai_chung_thu_so,
    (
      select case
        when lower(coalesce(lt.ten_loai, '')) like '%sim%' then 'Sim PKI'
        when lower(coalesce(lt.ten_loai, '')) like '%token%' then lt.ten_loai
        else null
      end
      from public.thiet_bi tb
      left join public.loai_thiet_bi lt on lt.id = tb.loai_thiet_bi_id
      where tb.id = cts.thiet_bi_id
    )
  ),
  la_hien_hanh = case when cts.thoi_diem_thu_hoi is null then cts.la_hien_hanh else false end;

create unique index if not exists idx_thiet_bi_chung_thu_so_one_current
  on public.thiet_bi_chung_thu_so (thiet_bi_id)
  where la_hien_hanh is true and thoi_diem_thu_hoi is null;

create index if not exists idx_thiet_bi_chung_thu_so_la_hien_hanh
  on public.thiet_bi_chung_thu_so (la_hien_hanh);

create index if not exists idx_thiet_bi_chung_thu_so_chung_thu_goc_id
  on public.thiet_bi_chung_thu_so (chung_thu_goc_id);

create index if not exists idx_thiet_bi_chung_thu_so_chung_thu_thay_the_id
  on public.thiet_bi_chung_thu_so (chung_thu_thay_the_id);

create index if not exists idx_thiet_bi_chung_thu_so_email
  on public.thiet_bi_chung_thu_so (email);

create index if not exists idx_thiet_bi_chung_thu_so_id_nguon
  on public.thiet_bi_chung_thu_so (id_chung_thu_so_nguon);

alter table public.lich_su_chung_thu_so
  add column if not exists thiet_bi_chung_thu_so_id integer references public.thiet_bi_chung_thu_so(id) on delete set null,
  add column if not exists email_truoc character varying,
  add column if not exists email_sau character varying,
  add column if not exists ten_chung_thu_so_truoc character varying,
  add column if not exists ten_chung_thu_so_sau character varying,
  add column if not exists to_chuc_truoc character varying,
  add column if not exists to_chuc_sau character varying,
  add column if not exists thong_tin_chung_truoc text,
  add column if not exists thong_tin_chung_sau text,
  add column if not exists noi_dung_thay_doi text,
  add column if not exists thong_tin_moi text,
  add column if not exists ly_do_thu_hoi text,
  add column if not exists mau_van_ban character varying;

create index if not exists idx_lich_su_chung_thu_so_record_id
  on public.lich_su_chung_thu_so (thiet_bi_chung_thu_so_id);

create table if not exists public.cau_hinh_van_ban_chung_thu_so (
  id integer generated by default as identity primary key,
  ten_co_quan_chu_quan character varying,
  ten_co_quan character varying,
  so_van_ban_mac_dinh character varying,
  dia_diem character varying,
  nguoi_dau_moi character varying,
  so_dinh_danh character varying,
  ngay_cap_dinh_danh date,
  noi_cap_dinh_danh character varying,
  chuc_vu_dau_moi character varying,
  dien_thoai_dau_moi character varying,
  email_dau_moi character varying,
  dia_chi_tiep_nhan text,
  nguoi_ky character varying,
  chuc_vu_nguoi_ky character varying,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

alter table public.cau_hinh_van_ban_chung_thu_so enable row level security;

drop trigger if exists set_cau_hinh_van_ban_chung_thu_so_updated_at
  on public.cau_hinh_van_ban_chung_thu_so;

create trigger set_cau_hinh_van_ban_chung_thu_so_updated_at
before update on public.cau_hinh_van_ban_chung_thu_so
for each row
execute function private.set_updated_at();

drop policy if exists cau_hinh_van_ban_chung_thu_so_read_authenticated
  on public.cau_hinh_van_ban_chung_thu_so;
drop policy if exists cau_hinh_van_ban_chung_thu_so_insert_staff
  on public.cau_hinh_van_ban_chung_thu_so;
drop policy if exists cau_hinh_van_ban_chung_thu_so_update_staff
  on public.cau_hinh_van_ban_chung_thu_so;
drop policy if exists cau_hinh_van_ban_chung_thu_so_delete_staff
  on public.cau_hinh_van_ban_chung_thu_so;

create policy cau_hinh_van_ban_chung_thu_so_read_authenticated
  on public.cau_hinh_van_ban_chung_thu_so
  for select to authenticated using (true);
create policy cau_hinh_van_ban_chung_thu_so_insert_staff
  on public.cau_hinh_van_ban_chung_thu_so
  for insert to authenticated with check ((select private.is_staff()));
create policy cau_hinh_van_ban_chung_thu_so_update_staff
  on public.cau_hinh_van_ban_chung_thu_so
  for update to authenticated using ((select private.is_staff())) with check ((select private.is_staff()));
create policy cau_hinh_van_ban_chung_thu_so_delete_staff
  on public.cau_hinh_van_ban_chung_thu_so
  for delete to authenticated using ((select private.is_staff()));

grant select, insert, update, delete on public.cau_hinh_van_ban_chung_thu_so to authenticated;
grant usage, select on sequence public.cau_hinh_van_ban_chung_thu_so_id_seq to authenticated;

drop view if exists public.v_bao_cao_chung_thu_so;

create view public.v_bao_cao_chung_thu_so
with (security_invoker = true)
as
select
  cts.id as thiet_bi_chung_thu_so_id,
  tb.id as thiet_bi_id,
  tb.ma_thiet_bi as so_hieu_thiet_bi,
  tb.ten_thiet_bi,
  lt.id as loai_thiet_bi_id,
  lt.ten_loai as loai_thiet_bi,
  nd.id as nguoi_su_dung_id,
  nd.ho_ten as nguoi_su_dung,
  coalesce(nd.phong_ban_id, tb.phong_ban_id) as phong_ban_id,
  pb.ten_phong_ban,
  cts.so_hieu_chung_thu_so,
  cts.email,
  cts.ten_chung_thu_so,
  cts.loai_chung_thu_so,
  cts.to_chuc,
  cts.thong_tin_chung,
  cts.id_chung_thu_so_nguon,
  cts.da_gia_han,
  cts.la_hien_hanh,
  cts.chung_thu_goc_id,
  cts.chung_thu_thay_the_id,
  cts.ngay_hieu_luc,
  cts.ngay_het_hieu_luc,
  cts.han_gia_han_lan_dau,
  cts.thoi_diem_gia_han_gan_nhat,
  cts.thoi_diem_thay_doi_thong_tin_gan_nhat,
  cts.thoi_diem_thu_hoi,
  cts.ly_do_thu_hoi,
  coalesce(
    cts.han_gia_han_lan_dau,
    case when cts.chung_thu_goc_id is not null then cts.ngay_het_hieu_luc else null end
  ) as ngay_can_thu_hoi,
  cts.ngay_het_hieu_luc - current_date as so_ngay_con_lai,
  case
    when cts.thoi_diem_thu_hoi is not null then 'da_thu_hoi'
    when cts.da_gia_han is true then 'da_gia_han'
    when cts.la_hien_hanh is false then 'da_thay_the'
    when cts.han_gia_han_lan_dau is not null and current_date > cts.han_gia_han_lan_dau then 'can_thu_hoi'
    when cts.chung_thu_goc_id is not null and current_date > cts.ngay_het_hieu_luc then 'can_cap_moi'
    when current_date > cts.ngay_het_hieu_luc then 'het_han'
    when cts.ngay_het_hieu_luc <= current_date + 30 then 'sap_het_han'
    else 'dang_hieu_luc'
  end as trang_thai,
  cts.ghi_chu,
  cts.created_at,
  cts.updated_at
from public.thiet_bi_chung_thu_so cts
join public.thiet_bi tb on tb.id = cts.thiet_bi_id
left join public.loai_thiet_bi lt on lt.id = tb.loai_thiet_bi_id
left join public.nguoi_dung nd on nd.id = cts.nguoi_su_dung_id
left join public.phong_ban pb on pb.id = coalesce(nd.phong_ban_id, tb.phong_ban_id);

grant select on public.v_bao_cao_chung_thu_so to authenticated;
revoke all on public.v_bao_cao_chung_thu_so from anon;

comment on table public.thiet_bi_chung_thu_so is
  'Vong doi chung thu so: mot thiet bi Token/Sim co nhieu serial CTS theo thoi gian, nhung chi mot CTS hien hanh.';
comment on column public.thiet_bi_chung_thu_so.la_hien_hanh is
  'Chi mot ban ghi la_hien_hanh=true va chua thu hoi tren moi thiet bi.';
comment on column public.thiet_bi_chung_thu_so.da_gia_han is
  'Danh dau CTS goc da duoc gia han mot lan; khong cho gia han tiep.';
comment on table public.cau_hinh_van_ban_chung_thu_so is
  'Cau hinh dau moi va van ban CTS dung khi xuat mau 04/05; khong hardcode thong tin ca nhan trong source code.';
comment on view public.v_bao_cao_chung_thu_so is
  'View bao cao vong doi CTS voi serial theo tung ban ghi va trang thai cap moi, gia han, thu hoi, thay the.';
